version: '3'

services:

  db:
    image: mongo:6.0
    container_name: ${MONGO_DB_NAME}
    volumes:
      - drinkology-vol:/data/db
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth']

  mongo-express:
    depends_on:
      - db
    container_name: ${EXPRESS_CONTAINER_NAME}
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8081:8081
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true 
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_NAME}
  
  #* Uncomment this code to run the server image locally:
  # app:
  #   depends_on:
  #     - db

  #   build:
  #     context: .
  #     target: ${STAGE}
  #     dockerfile: Dockerfile
    
  #   volumes:
  #     - .:/app/
  #     - /app/node_modules

  #   container_name: drinkology-server
  #   ports:
  #    - ${PORT}:${PORT}
  #   restart: always
  #   environment:
  #     PORT: ${PORT}
  #     SECRET_JWT_SEED: ${SECRET_JWT_SEED}
  #     MONGO_DB_CNN: ${MONGO_DB_CNN}
  #     EMAIL_USER: ${EMAIL_USER}
  #     EMAIL_PASSWORD: ${EMAIL_PASSWORD}
  #     EMAIL_COMMENTS_NOTIFICATION: ${EMAIL_COMMENTS_NOTIFICATION}

volumes:
  drinkology-vol:
    external: false